Repository preeti13456/CityonBikes, pull requests merged in 2021-01, with the labels that each got.

#27 Issue Template and PR Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: SWoC 2021, documentation, easy

#28 Ansh
  .idea/.gitignore
  .idea/.name
  .idea/CityonBikes.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Django1/urls.py
  app1/views.py
  requirements.txt
  static/images/Quote.jpg
  static/images/apache.jpg
  static/images/b2.jpg
  static/images/client/client-pic-1.jpg
  static/images/client/client-pic-4.jpg
  static/images/client/client-pic-5.jpg
  static/images/road.jpg
  templates/about.html
  templates/home.html
  templates/login.html
  templates/offer.html
Labels: SWoC 2021, enhancement, medium

#38 Added Tick Icon in qrcode page
  static/images/tickk.png
  templates/qrcode_page.html
Labels: SWoC 2021, enhancement, good first issue, medium

#53 geoloacion
  templates/rent_now.html
Labels: SWoC 2021, enhancement, help wanted, medium

#55 Added payment gateway
  app1/views.py
  templates/confirm_order.html
  templates/order.html
Labels: SWoC 2021, enhancement, hard

#56 Updated login page #30
  templates/login.html
Labels: SWoC 2021, enhancement, help wanted, medium

#62 Welcome bot
  .github/config.yml
Labels: SWoC 2021, enhancement, hard
